### ISSUE TITLE
Authentication 확인 부탁

### ISSUE THREAD

**Issue by yym0329** [gdsc-kaist/board-of-audit-and-inspection-system#16]
1. 유저 세션으로부터 user.organizationId 확인하는 방식이 맞는지
2. Authentication이 필요한 API들 리스트 

확인 부탁합니다!!

----
1. ERD를 봤을 때는 user 모델에 organization_id와 관련된 부분이 있는 것 같던데, 지금은 user 모델에 organization 관련 부분이 없는 것 같아요. 이거는 아직 구현을 안 한 건가요 아니면 ERD가 수정된 건가요?

2. user 데이터 모델에 organization이 들어간다는 가정 하에 Authentication middle ware를 짰습니다.

3. 유저 세션으로부터 organization id를 가져와서, request params에 있는 organization id와 비교하는 식으로 authentication을 했습니다.

4. feat/access_control 브랜치의 middleware 폴더에  미들웨어가 있습니다.

5. 예산안 API 중 예산안 등록/삭제, 보고서 조회 API에 Authentication을 적용했습니다. 지출증빙내역 업로드 API에 authentication을 적용했습니다.

**Comment by Byunk** [comment]
@yym0329 확인했고, middleware는 좋은 것 같아요. API 리스트에 대해서는 수정할 부분이 좀 있을 것 같은데, 우선 PR 올라와 있는 브랜치랑 merge 해주실 수 있을까요?
master 브랜치의 수정사항이 좀 있어서 이 부분을 먼저 합친 뒤에 API 리스트에 업데이트 하면 좋을 것 같습니다.

**Comment by yym0329** [comment]
@Byunk  feat/access_control 브랜치와 merge 했습니다!
