### ISSUE TITLE
swagger documentation - expense, income 관련 부분 수정 필요한지 검토

### ISSUE THREAD

**Issue by yym0329** [gdsc-kaist/board-of-audit-and-inspection-system#25]
@Byunk 

swagger documentation의 income, expense 부분에서, put, delete method 주소가 잘못된 거 같아요
현재는 `PUT: /budgets/expense/:budget_id:` 이렇게 되어 있는데, `PUT: /budgets/expense/:expense_id:` 이런 식으로 바뀌어야 할 것 같아요. router 코드 읽어 봤을 때 아마도 이게 맞는 것 같은데 검토 부탁합니다 !

**Comment by Byunk** [comment]
@yym0329 수정 필요한 부분이 맞는 것 같아요. 이런 이슈는 가능하다면 수정한 후 바로 PR 만들어서 올려줘도 될 것 같습니다!
