### ISSUE TITLE
API 권한에 대한 질문

### ISSUE THREAD

**Issue by yym0329** [gdsc-kaist/board-of-audit-and-inspection-system#6]
요약: 현재 진행 상태 업데이트 및 API 권한 제가 생각하고 있는 것이 맞는지 확인 부탁합니다. 진행된 것은 feat/access_control 브랜치에 푸시해놨습니다

### 현재 진행된 것

1. [post: /users]-유저 생성하는 API에서 request body에 생성하는 유저의 role을 기입하도록 router 내용을 수정하였습니다. 그리고 이 내용을 swagger documentation에 반영했습니다.
2. Budgets 관련 API의 security 관련 정보를 Swagger documentation에 추가했습니다. 감사기간 등록 및 수정 API에서만 admin authorization을 요구하는 것으로 해놨습니다. 
3. middleware/validate.ts에 있는 validateIsAdmin 함수를 Authorization 미들웨어로 사용했습니다. 
4. Swagger를 활용하여 organization 생성 -> 유저 생성 -> 로그인 -> 미들웨어 작동 확인 (admin, user 두 케이스 모두 확인함)했습니다

--- 
### API 권한 피드백
미들웨어가 잘 작동하는 것을 확인했기 때문에, API들의 권한만 명확히 확인하면 바로 Authorization은 완료할 수 있을 것 같아요. 

그래서 API들 중 Admin만 접근할 수 있는 API들이 다음 목록에 있는 것들이 맞는지 확인 부탁합니다.

- organization 관련 API 전부
- GET: /budgets 예산안 조회 기능은 어드민만 쓰는 건지 유저도 쓰는건지 헷갈립니다. 일단은 유저 입장에서도 전체 내역 확인할 필요가 있을 것 같아 user도 사용 가능이라 생각합니다.
- GET:/transactions 위와 같습니다
- GET:/users
- POST:/users 어드민만 유저 생성할 수 있도록 추가하는 것이 필요해 보였습니다
- PUT:/users/disable
- PUT:/users/enable

**Comment by Byunk** [comment]
@yym0329 기본적으로 `GET /budgets`과 `GET /transactions` API에 대해서는 admin 권한만 주는 것이 적절해 보입니다. 추후 유저가 지난 예산안을 조회할 수 있도록 API 추가 혹은 기능 확장이 필요할 것 같습니다. 나머지는 좋아보입니다..!
